name: 'purge-workflow-runs'
description: 'action to purge workflow runs'
author: 'Jonas Strassel'
branding:
  icon: minus-circle
  color: blue
inputs:
  days-old:
    required: false
    description: 'least days the runs have to be old to get purged'
    default: '30'
runs:
  using: 'node16'
  main: 'dist/index.js'
